name: Continuous Integration

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: |
          npm install
      - name: Lint and build
        run: |
          npm run lint
          npm run rollup
          npm run babel
